openapi: 3.0.3
info:
  title: Ecomm
  version: 1.0.0
paths:
  /api/categories:
    get:
      description: get a list of all categories
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /api/categories/{id}:
    get:
      description: get a category by id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        404:
          description: Category not found
          content:
            application/json:
              example: 'Not Found'
  /api/admin/categories:
    post:
      description: create a new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
  /api/admin/categories/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    delete:
      description: delete a category by id
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              example: 'Category deleted'
        404:
          description: Category not found
          content:
            application/json:
              example: 'Not Found'
    put:
      description: update a category by id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        201:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        404:
          description: Category not found
          content:
            application/json:
              example: 'Not Found'
    patch:
      description: activate a category by id
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              example: 'Category activated'
        404:
          description: Category not found
          content:
            application/json:
              example: 'Not Found'
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: string
          format: ObjectId
          example: ObjectId('648cbbc7a9f51e9aed992d95')
        nome:
          type: string
          example: 'INFORMÁTICA'
        status:
          type: string
          example: 'ATIVA'
          enum:
            - 'ATIVA'
            - 'INATIVA'
